{"kind":"symbol","identifier":{"url":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SDKError\/urlRequestFailed(error:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","externalID":"s:10DigiMeCore8SDKErrorO16urlRequestFailedyACs5Error_p_tcACmF","title":"SDKError.urlRequestFailed(error:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlRequestFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"DigiMeCore"}],"symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"urlRequestFailed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/digimecore\/sdkerror\/urlrequestfailed(error:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"An error occurred when communicating with digi.me server. Contains underlying error - typically an instance of URLError","type":"text"}],"hierarchy":{"paths":[["doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore","doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SDKError"]]},"sections":[],"references":{"doc://digimecore.DigiMeCore/documentation/DigiMeCore":{"url":"\/documentation\/digimecore","abstract":[],"role":"collection","identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore","kind":"symbol","title":"DigiMeCore","type":"topic"},"doc://digimecore.DigiMeCore/documentation/DigiMeCore/SDKError":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SDKError","kind":"identifier"}],"type":"topic","url":"\/documentation\/digimecore\/sdkerror","abstract":[{"text":"SDK Errors","type":"text"}],"title":"SDKError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDKError"}],"identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SDKError"},"doc://digimecore.DigiMeCore/documentation/DigiMeCore/SDKError/urlRequestFailed(error:)":{"type":"topic","identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SDKError\/urlRequestFailed(error:)","url":"\/documentation\/digimecore\/sdkerror\/urlrequestfailed(error:)","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"urlRequestFailed","kind":"identifier"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"role":"symbol","title":"SDKError.urlRequestFailed(error:)","abstract":[{"type":"text","text":"An error occurred when communicating with digi.me server. Contains underlying error - typically an instance of URLError"}]}}}