{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimecore\/syncerror\/message"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore","doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SyncError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/message"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DigiMeCore"}],"role":"symbol","symbolKind":"property","title":"message","externalID":"s:10DigiMeCore9SyncErrorV7messageSSSgvp","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"references":{"doc://digimecore.DigiMeCore/documentation/DigiMeCore/SyncError/message":{"abstract":[],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/digimecore\/syncerror\/message","identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/message","title":"message"},"doc://digimecore.DigiMeCore/documentation/DigiMeCore":{"role":"collection","title":"DigiMeCore","url":"\/documentation\/digimecore","abstract":[],"kind":"symbol","identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore","type":"topic"},"doc://digimecore.DigiMeCore/documentation/DigiMeCore/SyncError":{"identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SyncError","role":"symbol","kind":"symbol","title":"SyncError","url":"\/documentation\/digimecore\/syncerror","navigatorTitle":[{"kind":"identifier","text":"SyncError"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SyncError","kind":"identifier"}],"abstract":[{"text":"Reason why connecting to source or importing data from source into userâ€™s library failed","type":"text"}],"type":"topic"}}}