{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"DigiMeCore"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"symbolKind":"property","externalID":"s:10DigiMeCore9SyncErrorV7messageSSSgvp","roleHeading":"Instance Property","title":"message","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/message"},"hierarchy":{"paths":[["doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore","doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SyncError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimecore\/syncerror\/message"]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://digimecore.DigiMeCore/documentation/DigiMeCore/SyncError/message":{"kind":"symbol","title":"message","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/message","url":"\/documentation\/digimecore\/syncerror\/message","abstract":[]},"doc://digimecore.DigiMeCore/documentation/DigiMeCore":{"url":"\/documentation\/digimecore","abstract":[],"role":"collection","identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore","kind":"symbol","title":"DigiMeCore","type":"topic"},"doc://digimecore.DigiMeCore/documentation/DigiMeCore/SyncError":{"type":"topic","role":"symbol","title":"SyncError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SyncError","kind":"identifier"}],"url":"\/documentation\/digimecore\/syncerror","identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SyncError","kind":"symbol","abstract":[{"text":"Reason why connecting to source or importing data from source into userâ€™s library failed","type":"text"}],"navigatorTitle":[{"text":"SyncError","kind":"identifier"}]}}}