{"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"reauth","modules":[{"name":"DigiMeCore"}],"externalID":"s:10DigiMeCore9SyncErrorV6reauthSbSgvp","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"reauth","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reauth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore","doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SyncError"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/digimecore\/syncerror\/reauth"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/reauth"},"references":{"doc://digimecore.DigiMeCore/documentation/DigiMeCore/SyncError":{"type":"topic","role":"symbol","title":"SyncError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SyncError","kind":"identifier"}],"url":"\/documentation\/digimecore\/syncerror","identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SyncError","kind":"symbol","abstract":[{"text":"Reason why connecting to source or importing data from source into userâ€™s library failed","type":"text"}],"navigatorTitle":[{"text":"SyncError","kind":"identifier"}]},"doc://digimecore.DigiMeCore/documentation/DigiMeCore/SyncError/reauth":{"url":"\/documentation\/digimecore\/syncerror\/reauth","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reauth","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"title":"reauth","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/reauth"},"doc://digimecore.DigiMeCore/documentation/DigiMeCore":{"url":"\/documentation\/digimecore","abstract":[],"role":"collection","identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore","kind":"symbol","title":"DigiMeCore","type":"topic"}}}